### ISSUE TITLE
Intents to be imported.

### ISSUE THREAD

**Issue by jvsriniv** [cdimascio/nationalparks_conversation#8]
Thank you for the developerworks course and this example. 
I imported the conversation json in the resources folder as my workspace. That created the intents, entities and dialog flow as well as expected. 
I changed the conversation.js in the server code (commented the env) to get this working with IAM_apikey type of authentication and Watson Assistant.The conversation works perfectly.  Please see below:

![image](https://user-images.githubusercontent.com/40227444/41334330-e3fa6c40-6f02-11e8-95eb-42e62bfacf4e.png)

However, there is one issue with the intents as explained below. Please clarify.
When I type "Zion" instead of "Mount Zion" like above,  the #tellmeabout intent is not detected. i.e; the response only has in #yes and @NationalParks detected. 
Eventually, in the discoursehandler.js that interprets the response, the default case of the switch case is triggered. 
But this somehow results in "park" variable as undefined. Please see below.

![image](https://user-images.githubusercontent.com/40227444/41334445-41282074-6f03-11e8-936f-42765b16f56a.png)

Can you tell me the exact intents that you used for your application's (http://nationalparks.mybluemix.net/) workspace ?

I tried the workspace also directly and please find the intents detected.
![image](https://user-images.githubusercontent.com/40227444/41334568-ba54aa44-6f03-11e8-97a6-b22cfa176130.png)

![image](https://user-images.githubusercontent.com/40227444/41334596-d52c2428-6f03-11e8-8386-bfc3d4f676bd.png)

**Comment by cdimascio** [comment]
@jvsriniv Thanks for the issue submission.
This sounds like there may be problem with the training samples used for your intents...
[Here](https://github.com/cdimascio/nationalparks_conversation/blob/master/resources/conversation_workspace.json) is the `workspace.json` used in the [demo](http://nationalparks.mybluemix.net/). It contains all intents and training samples.
Please have a look at those. you can try pasting the contents of `workspace.json` into something like https://jsoneditoronline.org/ so that you can more easily navigate the json object.
